USE movies;

---Query 1---
SELECT m.TITLE, m.YEAR, m.LENGTH
FROM MOVIE AS m
WHERE (m.LENGTH > 120 OR m.LENGTH IS NULL) AND YEAR < 2000;

---Query 2---
SELECT NAME, GENDER
FROM MOVIESTAR
WHERE NAME LIKE 'J%' AND YEAR(BIRTHDATE) > 1948;

---Query 3---
SELECT s.NAME, COUNT(DISTINCT STARSIN.STARNAME) AS num_actors
FROM STUDIO AS s
JOIN MOVIE AS m ON m.STUDIONAME = s.NAME
JOIN STARSIN ON STARSIN.MOVIETITLE = m.TITLE
GROUP BY s.NAME;

---Query 4---	
SELECT MOVIESTAR.NAME, COUNT(s.MOVIETITLE) AS num_movies
FROM MOVIESTAR
LEFT JOIN STARSIN AS s ON MOVIESTAR.NAME = s.STARNAME
GROUP BY MOVIESTAR.NAME;

---Query 5---
SELECT s.NAME, m.TITLE, m.YEAR
FROM STUDIO AS s
JOIN MOVIE AS m on m.STUDIONAME = s.NAME
WHERE m.YEAR =
	(SELECT MAX(YEAR)
	 FROM MOVIE
	 WHERE STUDIONAME = s.NAME
	 GROUP BY STUDIONAME); 

---Query 6---
SELECT TOP 1 s.NAME
FROM MOVIESTAR AS s
WHERE s.GENDER = 'M'
ORDER BY s.BIRTHDATE DESC;

---Query 7---
SELECT DISTINCT m1.STUDIONAME, s1.STARNAME, Counts.StarCount
FROM MOVIE AS m1
JOIN STARSIN AS s1 ON m1.TITLE = s1.MOVIETITLE
JOIN (
    SELECT m.STUDIONAME, s.STARNAME, COUNT(s.STARNAME) AS StarCount
    FROM MOVIE AS m
    JOIN STARSIN AS s ON s.MOVIETITLE = m.TITLE
    GROUP BY m.STUDIONAME, s.STARNAME
) AS Counts ON m1.STUDIONAME = Counts.STUDIONAME AND s1.STARNAME = Counts.STARNAME
WHERE s1.STARNAME = (
    SELECT TOP 1 s.STARNAME
    FROM MOVIE AS m
    JOIN STARSIN AS s ON s.MOVIETITLE = m.TITLE
    WHERE m.STUDIONAME = m1.STUDIONAME
    GROUP BY m.STUDIONAME, s.STARNAME
    ORDER BY COUNT(s.STARNAME) DESC
);

---Query 8---
SELECT s.MOVIETITLE, s.MOVIEYEAR, COUNT(s.STARNAME) AS num_actors
FROM STARSIN AS s
GROUP BY s.MOVIETITLE, s.MOVIEYEAR
HAVING COUNT(s.STARNAME) > 2;
