USE ships;

---Query 1---
SELECT o.SHIP
FROM OUTCOMES AS o
WHERE o.SHIP LIKE 'C%' OR o.SHIP LIKE 'K%'
GROUP BY o.SHIP
HAVING COUNT(o.RESULT) >= 1;

---Query 2---
SELECT DISTINCT s.NAME, c.COUNTRY
FROM SHIPS AS s
JOIN CLASSES AS c ON c.CLASS = s.CLASS
LEFT JOIN OUTCOMES AS o ON o.SHIP = s.NAME
WHERE (SELECT COUNT(*) 
       FROM OUTCOMES AS o1
	   WHERE o1.RESULT = 'sunk' AND o1.SHIP = o.SHIP
) = 0 OR o.SHIP IS NULL;

---Query 3---
SELECT c.COUNTRY, COUNT(sunk_ships.SHIP) AS num_sunk_ships
FROM CLASSES AS c
LEFT JOIN SHIPS AS s ON s.CLASS = c.CLASS
LEFT JOIN (
	SELECT DISTINCT o.SHIP
	FROM OUTCOMES AS o
	WHERE o.RESULT = 'sunk'
) AS sunk_ships ON s.NAME = sunk_ships.SHIP
GROUP BY c.COUNTRY;

SELECT * FROM OUTCOMES;

---Query 4---
SELECT o.BATTLE
FROM OUTCOMES AS o
GROUP BY o.BATTLE
HAVING COUNT(o.SHIP) > (
	SELECT COUNT(o2.SHIP)
	FROM OUTCOMES AS o2
	WHERE o2.BATTLE = 'Guadalcanal'
	GROUP BY o2.BATTLE
);

---Query 5---
SELECT o.BATTLE
FROM OUTCOMES AS o
GROUP BY o.BATTLE
HAVING COUNT(o.SHIP) > (
	SELECT COUNT(o2.SHIP)
	FROM OUTCOMES AS o2
	WHERE o2.BATTLE = 'Surigao Strait'
	GROUP BY o2.BATTLE
);

---Query 6---
SELECT s.NAME, c.DISPLACEMENT, c.NUMGUNS
FROM SHIPS AS s
JOIN CLASSES AS c ON c.CLASS = s.CLASS
WHERE c.DISPLACEMENT = (SELECT MIN(DISPLACEMENT) FROM CLASSES)
AND c.NUMGUNS = (
	SELECT MAX(min_displacement.NUMGUNS) 
	FROM (
		SELECT s.NAME, c.DISPLACEMENT, c.NUMGUNS
		FROM SHIPS AS s
		JOIN CLASSES AS c ON c.CLASS = s.CLASS
		WHERE c.DISPLACEMENT = (SELECT MIN(DISPLACEMENT) FROM CLASSES)
	) AS min_displacement
);

---Query 7---
SELECT COUNT(*) AS num_ships
FROM BATTLES AS b
JOIN OUTCOMES AS o ON o.BATTLE = b.NAME
WHERE o.RESULT = 'damaged'
AND o.SHIP IN (
	SELECT o2.SHIP
	FROM OUTCOMES AS o2
	JOIN BATTLES AS b2 ON o2.BATTLE = b2.NAME
	WHERE b2.DATE > b.DATE AND o2.RESULT = 'ok' 
);

---Query 8---
SELECT o.SHIP
FROM BATTLES AS b
JOIN OUTCOMES AS o ON o.BATTLE = b.NAME
WHERE o.RESULT = 'damaged'
AND o.SHIP IN (
	SELECT o2.SHIP
	FROM OUTCOMES AS o2
	JOIN BATTLES AS b2 ON o2.BATTLE = b2.NAME
	WHERE b2.DATE > b.DATE AND o2.RESULT = 'ok'
	AND o2.BATTLE IN (
		SELECT o3.BATTLE
		FROM OUTCOMES AS o3
		GROUP BY o3.BATTLE
		HAVING COUNT(o3.SHIP) > (
			SELECT COUNT(o4.SHIP)
			FROM OUTCOMES AS o4
			WHERE o4.BATTLE = o.BATTLE 
			GROUP BY o4.BATTLE
		)
	)
);
