USE movies;

---Query 1---
INSERT INTO MOVIESTAR(NAME, BIRTHDATE)
VALUES('Nicole Kidman', '1967-06-20');

---Query 2---
DELETE FROM MOVIEEXEC
WHERE NETWORTH < 30000000;

---Query 3---
DELETE FROM MOVIESTAR
WHERE ADDRESS IS NULL;
