USE ships;

---Query 1---
INSERT INTO CLASSES
VALUES('Nelson', 'bb', 'Gt. Britain', 9, 16, 34000);

INSERT INTO SHIPS
VALUES
	('Nelson', 'Nelson', 1927),
	('Rodney', 'Nelson', 1927)
;

---Query 2---
DELETE FROM SHIPS
WHERE SHIPS.NAME IN (
	SELECT DISTINCT s.NAME
	FROM SHIPS AS s
	JOIN OUTCOMES AS o ON s.NAME = o.SHIP
	WHERE o.RESULT = 'sunk'
);

---Query 3---
UPDATE CLASSES
SET CLASSES.BORE = 2.5 * CLASSES.BORE;

UPDATE CLASSES
SET CLASSES.DISPLACEMENT = 1.1 * CLASSES.DISPLACEMENT;
