USE ships;

---Query 1---
SELECT s.NAME
FROM SHIPS AS s, CLASSES AS c
WHERE s.CLASS = c.CLASS
AND c.DISPLACEMENT > 50000;

---Query 2---
SELECT s.NAME, c.DISPLACEMENT, c.NUMGUNS
FROM SHIPS AS s, CLASSES AS c, OUTCOMES AS o
WHERE s.CLASS = c.CLASS
AND o.SHIP = s.NAME
AND o.BATTLE = 'Guadalcanal';

---Query 3---
SELECT DISTINCT c1.COUNTRY
FROM CLASSES AS c1, CLASSES AS c2
WHERE c1.TYPE = 'bc'
AND c2.TYPE = 'bb'
AND c1.COUNTRY = c2.COUNTRY;

---Query 4---
SELECT * FROM outcomes;
SELECT DISTINCT o1.SHIP
FROM OUTCOMES AS o1, OUTCOMES as o2
WHERE o1.SHIP = o2.SHIP
AND o1.RESULT = 'damaged'
AND o2.RESULT != 'damaged'
AND o1.BATTLE != o2.BATTLE;
