USE movies;

---Query 1---
SELECT ADDRESS
FROM STUDIO
WHERE NAME ='Disney';

---Query 2---
SELECT BIRTHDATE
FROM MOVIESTAR
WHERE NAME = 'Jack Nicholson';

---Query 3---
SELECT STARNAME
FROM STARSIN
WHERE MOVIEYEAR = 1980 OR MOVIETITLE LIKE '%Knight%';

---Query 4---
SELECT NAME
FROM MOVIEEXEC
WHERE NETWORTH > 10000000;

---Query 5---
SELECT NAME
FROM MOVIESTAR
WHERE GENDER = 'M' OR ADDRESS = 'Prefect Rd.';
