USE ships;

---Query 1---
SELECT COUNT(CLASS) AS 'NO_Classes'
FROM CLASSES
WHERE TYPE = 'bb';

---Query 2---
SELECT CLASS, AVG(NUMGUNS) AS 'avgGuns'
FROM CLASSES
WHERE TYPE = 'bb'
GROUP BY CLASS;

---Query 3---
SELECT AVG(NUMGUNS) AS 'avgGuns'
FROM CLASSES
WHERE TYPE = 'bb';

---Query 4---
SELECT CLASSES.CLASS, MIN(SHIPS.LAUNCHED) AS 'FirstYear', MAX(SHIPS.LAUNCHED) AS 'LastYear'
FROM CLASSES
JOIN SHIPS ON CLASSES.CLASS = SHIPS.CLASS
GROUP BY CLASSES.CLASS;

---Query 5---
SELECT SHIPS.CLASS, COUNT(*) AS 'No_Sunk'
FROM SHIPS
JOIN OUTCOMES ON SHIPS.NAME = OUTCOMES.SHIP
WHERE OUTCOMES.RESULT = 'sunk'
GROUP BY SHIPS.CLASS;

---Query 6---
SELECT SHIPS.CLASS, COUNT(*) AS 'No_Sunk'
FROM SHIPS
JOIN OUTCOMES ON SHIPS.NAME = OUTCOMES.SHIP
WHERE OUTCOMES.RESULT = 'sunk'
GROUP BY SHIPS.CLASS
HAVING SHIPS.CLASS IN (
	SELECT CLASSES.CLASS
	FROM CLASSES
	JOIN SHIPS ON CLASSES.CLASS = SHIPS.CLASS
	GROUP BY CLASSES.CLASS
	HAVING COUNT(SHIPS.NAME) > 2
);

---Query 7---
SELECT CLASSES.COUNTRY, ROUND(AVG(CLASSES.BORE), 2) AS 'avg_bore'
FROM CLASSES
JOIN SHIPS ON CLASSES.CLASS = SHIPS.CLASS
GROUP BY COUNTRY;
