USE movies;

---Query 1---
SELECT m.TITLE, e.NAME 
FROM MOVIE AS m
JOIN MOVIEEXEC AS e ON m.PRODUCERC# = e.CERT#
WHERE e.NAME = 'George Lucas';

---Query 2---
SELECT DISTINCT e.NAME
FROM MOVIE AS m
JOIN MOVIEEXEC AS e ON m.PRODUCERC# = e.CERT#
JOIN STARSIN AS s ON m.TITLE = s.MOVIETITLE
WHERE s.STARNAME = 'Harrison Ford';

---Query 3---
SELECT DISTINCT m.STUDIONAME, s.STARNAME
FROM MOVIE AS m
JOIN STARSIN AS s ON m.TITLE = s.MOVIETITLE;

---Query 4---
SELECT s.STARNAME, e.NETWORTH, m.TITLE
FROM MOVIE AS m
JOIN MOVIEEXEC AS e ON m.PRODUCERC# = e.CERT#
JOIN STARSIN AS s ON m.TITLE = s.MOVIETITLE
WHERE e.CERT# IN (
	SELECT TOP 1 CERT#
	FROM MOVIEEXEC AS e2
	WHERE e2.NETWORTH >= ALL(SELECT NETWORTH FROM MOVIEEXEC)
);

---Query 5---
SELECT ms.NAME, s.MOVIETITLE 
FROM MOVIESTAR AS ms
LEFT JOIN STARSIN AS s ON ms.NAME = s.STARNAME
WHERE s.MOVIETITLE IS NULL;
