USE ships;

---Query 1---
SELECT * 
FROM SHIPS AS s
INNER JOIN CLASSES AS c ON s.CLASS = c.CLASS;

---Query 2---
SELECT * 
FROM SHIPS AS s
FULL JOIN CLASSES AS c ON s.CLASS = c.CLASS
WHERE c.CLASS IS NOT NULL OR c.CLASS IN (SELECT NAME FROM SHIPS);

---Query 3---
SELECT c.COUNTRY, s.NAME
FROM CLASSES AS c
JOIN SHIPS AS s ON c.CLASS = s.CLASS
FULL JOIN OUTCOMES AS o ON o.SHIP = s.NAME
WHERE o.SHIP IS NULL
ORDER BY c.COUNTRY, s.NAME;

---Query 4---
SELECT s.NAME AS 'Ship Name'
FROM CLASSES AS c
JOIN SHIPS AS s ON c.CLASS = s.CLASS
WHERE c.NUMGUNS >= 7  AND s.LAUNCHED = 1916;

---Query 5---
SELECT o.SHIP, o.BATTLE, b.DATE
FROM OUTCOMES AS o
JOIN BATTLES AS b ON o.BATTLE = b.NAME
WHERE o.RESULT = 'sunk'
ORDER BY o.BATTLE;

---Query 6---
SELECT s.NAME, c.DISPLACEMENT, s.LAUNCHED 
FROM SHIPS AS s
JOIN CLASSES AS c ON s.CLASS = c.CLASS
WHERE s.NAME = s.CLASS;

---Query 7---
SELECT *
FROM CLASSES
WHERE CLASS NOT IN (
	SELECT c.CLASS
	FROM CLASSES AS c
	JOIN SHIPS AS s ON c.CLASS = s.CLASS
);

---Query 8---
SELECT s.NAME, c.DISPLACEMENT, c.NUMGUNS, o.RESULT
FROM SHIPS AS s
JOIN CLASSES AS c ON s.CLASS = c.CLASS
JOIN OUTCOMES AS o ON s.NAME = o.SHIP
WHERE o.BATTLE = 'North Atlantic';
