USE movies;

---Query 1---
SELECT s.NAME 
FROM MOVIESTAR AS s
WHERE s.NAME IN (
	SELECT e.NAME 
	FROM MOVIEEXEC AS e
	WHERE e.NETWORTH > 10000000
);

---Query 2---
SELECT s.NAME
FROM MOVIESTAR AS s
WHERE s.NAME NOT IN (
	SELECT e.NAME 
	FROM MOVIEEXEC AS e
);

---Query 3---
SELECT m.TITLE
FROM MOVIE AS m
WHERE m.LENGTH > (
	SELECT m2.LENGTH
	FROM MOVIE AS m2
	WHERE m2.TITLE = 'Star Wars'
);

---Query 4---
SELECT m.TITLE, e.NAME
FROM MOVIE AS m
JOIN MOVIEEXEC AS e ON m.PRODUCERC# = e.CERT#
WHERE e.NETWORTH > (
	SELECT e2.NETWORTH
	FROM MOVIEEXEC AS e2
	WHERE e2.NAME = 'Merv Griffin' 
);
