USE ships;

---Query 1---
SELECT DISTINCT COUNTRY
FROM CLASSES
WHERE NUMGUNS >= ALL (
	SELECT NUMGUNS
	FROM CLASSES
);

---Query 2---
SELECT DISTINCT C.CLASS
FROM CLASSES AS C
JOIN SHIPS ON C.CLASS = SHIPS.CLASS
JOIN OUTCOMES AS O ON SHIPS.NAME = O.SHIP
WHERE O.RESULT  = 'sunk'

---Query 3---
SELECT NAME, SHIPS.CLASS
FROM SHIPS
JOIN CLASSES AS C ON SHIPS.CLASS = C.CLASS
WHERE C.BORE = 16;

---Query 4---
SELECT DISTINCT BATTLE
FROM OUTCOMES
JOIN SHIPS ON OUTCOMES.SHIP = SHIPS.NAME
WHERE SHIPS.CLASS = 'Kongo'; 

---Query 5---
SELECT C.CLASS, S.NAME 
FROM CLASSES AS C
JOIN SHIPS AS S ON C.CLASS = S.CLASS
WHERE C.NUMGUNS >= ALL (
	SELECT C2.NUMGUNS
	FROM CLASSES AS C2
	WHERE C2.BORE = C.BORE
);